#!/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme spiral
bspc config initial_polarity first_child

bspc config normal_border_color  "#0a1011"
bspc config focused_border_color "#f8f8f2"
bspc config focus_follows_pointer true

bspc rule -a Brave-browser desktop='^2' state=tiled follow=on
bspc rule -a discord       desktop='^7' state=tiled follow=on
bspc rule -a Steam         desktop='^8' state=tiled follow=on
bspc rule -a Lxappearance  state=floating follow=on
bspc rule -a openrgb       state=floating follow=on
bspc rule -a Piper         state=floating follow=on
bspc rule -a Pavucontrol   state=floating follow=on

$HOME/.config/bspwm/autostart.sh
