#!/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         1
bspc config window_gap           15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme spiral
bspc config initial_polarity first_child

bspc config normal_border_color  "#0D1117"
bspc config focused_border_color "#C9D1D9"
bspc config focus_follows_pointer true

bspc rule -a Brave-browser desktop='^2' state=tiled follow=on
bspc rule -a discord       desktop='^7' state=tiled follow=on
bspc rule -a Steam         desktop='^8' state=tiled follow=off
bspc rule -a thunderbird   desktop='^3' state=tiled follow=on
bspc rule -a Virt-manager  desktop='^9' state=tiled follow=on
bspc rule -a Zathura	   state=tiled    follow=on
bspc rule -a Gpick         state=floating follow=on
bspc rule -a Lxappearance  state=floating follow=on
bspc rule -a openrgb       state=floating follow=on
bspc rule -a Piper         state=floating follow=on
bspc rule -a Pavucontrol   state=floating follow=on

$HOME/.config/bspwm/autostart
